token: '' # Account token of Discord bot.
port: '1880' # Port to listen incoming events on.

# GitHub webhooks.
git:
  webhookid: ''
  webhooktoken: ''
  secret: '' # Local webhook secret for HMAC validation.
  endpoint: '' # Reachable endpoint path.
